In [13]:
url = "https://raw.githubusercontent.com/pia222sk20/python/refs/heads/main/pandas-data-analysis/part3/data/train.csv"

In [14]:
import pandas as pd
df = pd.read_csv(url)
df.head()

,id,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5,count
0,3,20,16.3,1.0,1.5,89.0,576.0,0.027,76.0,33.0,49.0
1,6,13,20.1,0.0,1.4,48.0,916.0,0.042,73.0,40.0,159.0
2,7,6,13.9,0.0,0.7,79.0,1382.0,0.033,32.0,19.0,26.0
3,8,23,8.1,0.0,2.7,54.0,946.0,0.040,75.0,64.0,57.0
4,9,18,29.5,0.0,4.8,7.0,2000.0,0.057,27.0,11.0,431.0

In [15]:
df.hour.value_counts()

hour
20    61
6     61
23    61
18    61
3     61
2     61
14    61
9     61
5     61
11    61
4     61
10    61
1     61
8     61
15    61
7     61
12    61
22    61
19    61
13    60
21    60
17    60
16    60
0     60
Name: count, dtype: int64

In [16]:
df[df.hour== 20]

,id,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5,count
0,3,20,16.3,1.0,1.5,89.0,576.0,0.027,76.0,33.0,49.0
50,84,20,15.6,0.0,3.2,30.0,1211.0,0.060,69.0,58.0,130.0
89,136,20,20.7,0.0,4.1,31.0,2000.0,0.043,40.0,13.0,191.0
102,157,20,11.4,0.0,2.5,85.0,716.0,0.033,38.0,26.0,102.0
112,170,20,16.9,0.0,3.4,63.0,1966.0,0.041,46.0,22.0,185.0
...,...,...,...,...,...,...,...,...,...,...,...
1398,2096,20,14.0,0.0,2.9,35.0,910.0,0.061,NaN,NaN,117.0
1401,2100,20,14.2,0.0,3.6,33.0,2000.0,0.035,42.0,20.0,138.0
1423,2131,20,19.6,0.0,1.7,66.0,1142.0,0.053,54.0,33.0,171.0
1434,2152,20,14.0,0.0,4.3,44.0,2000.0,0.043,48.0,19.0,150.0
1445,2163,20,21.5,0.0,1.0,33.0,2000.0,0.049,60.0,32.0,201.0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      1459 non-null   int64
 1   hour                    1459 non-null   int64
 2   hour_bef_temperature    1457 non-null   float64
 3   hour_bef_precipitation  1457 non-null   float64
 4   hour_bef_windspeed      1450 non-null   float64
 5   hour_bef_humidity       1457 non-null   float64
 6   hour_bef_visibility     1457 non-null   float64
 7   hour_bef_ozone          1383 non-null   float64
 8   hour_bef_pm10           1369 non-null   float64
 9   hour_bef_pm2.5          1342 non-null   float64
 10  count                   1459 non-null   float64
dtypes: float64(9), int64(2)
memory usage: 125.5 KB

In [20]:
# 시간에 따른 자전거 대여량 변화 추이
# 시간별 자전거 대여량

# count 열의 합계를 시간별로 그룹화
hour_sum_df = df.groupby('hour')['count'].sum()

# 그래프 그리기
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
hour_sum_df.plot(kind='line', marker='o')
plt.title('시간대별 자전거 대여량')
plt.xlabel('시간')
plt.ylabel('대여량')
plt.grid(True)
plt.show()

# 시간대별 대여량 데이터 출력
print("\n시간대별 대여량:")
print(hour_sum_df)

AttributeError: 'numpy.int64' object has no attribute 'plot'